import Link from 'next/link';
import styles from '../styles/articles.module.css'
import {getArticlesData} from "../libs/articles";
import HeaderBlock from "../compontents/HeaderBlock/HeaderBlock";
import {Button} from "@mui/material";
import {useState} from "react";
import Head from "next/head";

export default function Articles(pageData) {
    let articlesData = JSON.parse(pageData.res).data
    let pagination = JSON.parse(pageData.res).pagination
    const [data, setData] = useState(articlesData)
    const loadMore = async () => {
        const res = await getArticlesData(pagination.page + 1)
        pagination = JSON.parse(res).pagination
        setData(articlesData.concat(JSON.parse(res).data))
        console.log(res)
    }
    return (
        <div className={styles.container}>
            <Head>
                <title>Generated by Guo Liang</title>
                <meta name="description" content="Generated by Guo Liang"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.pageBody}>
                <HeaderBlock/>
                {data.map(article => (
                    data.indexOf(article) === 0 || data.indexOf(article) === 4 ?
                        <div key={article.id} id={data.indexOf(article)} className={styles.articleFullWidth}
                             style={{
                                 background: `url(${process.env.API_BASE_URL}${article.cover}) no-repeat`,
                                 backgroundSize: 'cover',

                             }}>
                            <div className={styles.featuredArticle}>
                                <div className={styles.featuredCategory}>
                                    {article.category}
                                </div>
                                <Link href={`/articles/${article.slug}`}>
                                    <a className={styles.featuredTitle}>{article.title}</a>
                                </Link>
                                <div className={styles.publishDate}>
                                    {article.publishedAt}
                                </div>
                                <div className={styles.articleDesc}>{article.description}</div>
                            </div>
                        </div>
                        : <div key={article.id} className={styles.articleHalfWidth}>
                            <div className={styles.halfWidthCover} style={{
                                background: `url(${process.env.API_BASE_URL}${article.cover}) no-repeat`,
                                backgroundSize: 'cover',
                                backgroundPosition: 'center'
                            }}/>
                            <div className={styles.halfWidthContent}>
                                <div className={styles.featuredCategory}>
                                    {article.category}
                                </div>
                                <Link href={`/articles/${article.slug}`}>
                                    <a className={styles.halfWidthContentTitle}>{article.title}</a>
                                </Link>
                                <div className={styles.publishDate}>
                                    {article.publishedAt}
                                </div>
                                <p className={styles.articleDesc}>{article.description}</p>
                            </div>
                        </div>
                ))}
                {data.length < pagination.total ? <Button onClick={loadMore}>查看更多文章</Button> : <></>}
            </div>
        </div>
    )
}

export async function getServerSideProps() {
    const res = await getArticlesData()
    return {
        props: {res}
    }
}