import styles from '../styles/Home.module.css'
import {Button, Container, Link, useMediaQuery} from "@mui/material";
import {useState} from "react";
import Head from "next/head";
import Image from 'next/image'
import {getArticlesData} from "../libs/articles";
import Layout from "../compontents/Layout/Layout";
import HeaderBlock from "../compontents/HeaderBlock/HeaderBlock";
import ArticlesList from "../compontents/ArticlesList/ArticlesList";

export default function Articles(pageData) {
    let articlesData = JSON.parse(pageData.res).data
    let pagination = JSON.parse(pageData.res).pagination
    const [data, setData] = useState(articlesData)
    const loadMore = async () => {
        const res = await getArticlesData(pagination.page + 1)
        pagination = JSON.parse(res).pagination
        setData(articlesData.concat(JSON.parse(res).data))
    }

    const headerPost = articlesData[0]
    const isMobile = useMediaQuery('(max-width: 600px)')

    return (
        <Container maxWidth={'xl'} disableGutters>
            <Head>
                <title>Generated by Guo Liang</title>
                <meta name="description" content="Generated by Guo Liang"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <HeaderBlock/>
            <Layout>
                <div className={styles.headerPost}>
                    <div className={styles.cover}>
                        <Image src={`${process.env.API_BASE_URL}${headerPost.cover}`}
                               layout={'fill'} objectFit={'cover'} priority={'true'} alt={headerPost.title}/>
                    </div>
                    <div className={styles.headerPostContent}>
                        <div className={styles.featuredCategory}>
                            {headerPost.category}
                        </div>
                        <Link href={`/articles/${headerPost.slug}`} className={styles.featuredTitle} color={'inherit'}
                              underline={'hover'}>
                            {headerPost.title}
                        </Link>
                        {isMobile
                            ? <></>
                            : <>
                                <div className={styles.publishedDate}>
                                    {headerPost.publishedAt}
                                </div>
                                <div className={styles.articleDesc}>{headerPost.description}</div>
                            </>
                        }
                    </div>
                </div>
                {data.length > 1 &&
                <ArticlesList articles={data.slice(1)}/>
                }
                {data.length < pagination.total ? <Button onClick={loadMore}>查看更多文章</Button> : <></>}
            </Layout>
        </Container>
    )
}

export async function getServerSideProps() {
    const res = await getArticlesData()
    return {
        props: {res}
    }
}