import Head from 'next/head'
import styles from '../styles/Home.module.css'

import {Button, Grid} from "@mui/material";
import {ImageList, ImageListItem, Link, makeStyles} from "@material-ui/core";
import BusinessCenterIcon from '@mui/icons-material/BusinessCenter';
import {getClientsData} from "../libs/clients";
//import {process} from "next/dist/server/web/sandbox/polyfills";

const useStyle = makeStyles({
    MainButton: {
        border: '2.5px solid',
        "&:hover": {
            border: '2.5px solid',
        }
    },
    Icon: {
        fill: '#007CED',
        fontSize: '2.5em',
    },

    ImageList: {
        flexWrap: 'nowrap',
        padding: '2em 0',
    },

    ImageListItemHeight: {
        height: 'auto',
        maxHeight: '50%',
        maxWidth: '90%'
    },

    ImageListItem: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center'
    },

    ImageListImages: {
        width: '100%',
        height: 'auto'
    }
})

export default function Home(resumeData) {
    const clients = JSON.parse(resumeData.clientsData)
    const classes = useStyle()
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.pageBody}>
                <header className={styles.header}>
                    <Grid container direction={'row'} justifyContent={'center'}>
                        <Grid item xs={7}>
                            <div className={styles.headerContent}>
                                <div className={styles.textLogo}>
                                    <div className={styles.logoSymbol}>G</div>
                                    <div className={styles.logoText}>
                                        test test
                                    </div>
                                </div>
                            </div>
                        </Grid>
                        <Grid item container xs={5} direction={"row"} alignItems={"center"}>
                            <Grid item xs={4}>
                                <Link href={'/articles'}>文章</Link>
                            </Grid>
                            <Grid item xs={4}>test</Grid>
                            <Grid item xs={4}>test</Grid>
                        </Grid>
                    </Grid>
                </header>
                <main>
                    <Grid container direction={"row"} justifyContent={"center"} className={styles.information}>
                        <Grid item container xs={10} justifyContent={"center"}>
                            <Grid item container xs={5}>
                                <div className={styles.photoContainer}>
                                    <div className={styles.photo}>
                                        <img src={'/img/INEAT.png'} className={styles.avatar} alt={'avatar'}/>
                                    </div>
                                </div>
                            </Grid>
                            <Grid item container xs={7}>
                                <div>
                                    <p className={styles.position}>
                                        Lorem ipsum dolor sit amet
                                    </p>
                                    <p className={styles.name}>
                                        郭亮
                                    </p>
                                    <p className={styles.description}>
                                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed eget fermentum
                                        quam, et volutpat augue. Fusce ut orci sed justo vehicula lobortis. Donec vitae
                                        pharetra augue. Nam dictum suscipit ipsum, vitae tristique libero gravida vel.
                                    </p>
                                </div>
                                <Grid container className={styles.buttonContainer} direction={"row"}
                                      alignItems={"flex-end"} justifyContent={"center"}>
                                    <Grid item container xs={4} justifyContent={"center"}>
                                        <Button variant="outlined" color={"primary"}
                                                classes={{root: classes.MainButton}} fullWidth={true}
                                                disableRipple={true}>Default</Button>
                                    </Grid>
                                    <Grid item xs={2}/>
                                    <Grid item container xs={4} justifyContent={"center"}>
                                        <Button variant="outlined" fullWidth={true} disableRipple={true}
                                                classes={{root: classes.MainButton}}>Default</Button>
                                    </Grid>
                                </Grid>
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid container direction={"row"}>
                        <Grid item xs={3}>
                            <h2 className={styles.h2}>Lorem ipsum</h2>
                        </Grid>
                        <Grid item container className={styles.skillsContent}>
                            <Grid item container xs={6}>
                                <Grid item xs={1}>
                                    <BusinessCenterIcon classes={{root: classes.Icon}}/>
                                </Grid>
                                <Grid item xs={9} className={styles.skill}>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Mi proin sed libero enim sed faucibus
                                    turpis. Rhoncus urna neque viverra justo nec ultrices dui. Mattis vulputate enim
                                    nulla aliquet porttitor lacus luctus accumsan tortor. Accumsan in nisl nisi
                                    scelerisque eu ultrices vitae auctor eu. Lacus sed turpis tincidunt id aliquet risus
                                    feugiat in ante. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada
                                    proin.
                                </Grid>
                            </Grid>
                            <Grid item container xs={6}>
                                <Grid item xs={1}>
                                    <BusinessCenterIcon classes={{root: classes.Icon}}/>
                                </Grid>
                                <Grid item xs={9} className={styles.skill}>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Mi proin sed libero enim sed faucibus
                                    turpis. Rhoncus urna neque viverra justo nec ultrices dui. Mattis vulputate enim
                                    nulla aliquet porttitor lacus luctus accumsan tortor. Accumsan in nisl nisi
                                    scelerisque eu ultrices vitae auctor eu. Lacus sed turpis tincidunt id aliquet risus
                                    feugiat in ante. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada
                                    proin.
                                </Grid>
                            </Grid>
                        </Grid>
                        <Grid item container className={styles.skillsContent}>
                            <Grid item container xs={6}>
                                <Grid item xs={1}>
                                    <BusinessCenterIcon classes={{root: classes.Icon}}/>
                                </Grid>
                                <Grid item xs={9} className={styles.skill}>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Mi proin sed libero enim sed faucibus
                                    turpis. Rhoncus urna neque viverra justo nec ultrices dui. Mattis vulputate enim
                                    nulla aliquet porttitor lacus luctus accumsan tortor. Accumsan in nisl nisi
                                    scelerisque eu ultrices vitae auctor eu. Lacus sed turpis tincidunt id aliquet risus
                                    feugiat in ante. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada
                                    proin.
                                </Grid>
                            </Grid>
                            <Grid item container xs={6}>
                                <Grid item xs={1}>
                                    <BusinessCenterIcon classes={{root: classes.Icon}}/>
                                </Grid>
                                <Grid item xs={9} className={styles.skill}>
                                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
                                    incididunt ut labore et dolore magna aliqua. Mi proin sed libero enim sed faucibus
                                    turpis. Rhoncus urna neque viverra justo nec ultrices dui. Mattis vulputate enim
                                    nulla aliquet porttitor lacus luctus accumsan tortor. Accumsan in nisl nisi
                                    scelerisque eu ultrices vitae auctor eu. Lacus sed turpis tincidunt id aliquet risus
                                    feugiat in ante. Tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada
                                    proin.
                                </Grid>
                            </Grid>
                        </Grid>
                    </Grid>
                    <Grid container direction={"row"} className={styles.clients}>
                        <Grid item xs={3}>
                            <h2 className={styles.h2}>服务客户</h2>
                        </Grid>
                        <ImageList classes={{root: classes.ImageList}} cols={7} gap={20}
                                   rowHeight={"auto"}
                                   className={styles.logos}>
                            {clients.data.map(client => (
                                <ImageListItem className={styles.imageListItem} classes={{root: classes.ImageListItem}}
                                               key={client.id}>
                                    <img className={styles.logoImages} style={{width: '100%', height: 'auto'}}
                                         src={`${process.env.API_BASE_URL}${client.attributes.logo.data.attributes.url}`}
                                         loading={'lazy'} alt={client.attributes.name}/>
                                </ImageListItem>
                            ))}
                        </ImageList>
                    </Grid>
                    <Grid container direction={"row"}>
                        <Grid item xs={3}>
                            <h2 className={styles.h2}>资质及证书</h2>
                        </Grid>
                        <ImageList classes={{root: classes.ImageList}} cols={4} gap={0} rowHeight={"auto"}
                                   className={styles.logos}>
                        </ImageList>
                    </Grid>
                </main>
                <footer></footer>
            </div>
        </div>
    )
}

export async function getServerSideProps() {
    const clientsData = await getClientsData()
    return {
        props: {clientsData}
    }
}
